apiVersion: v1
kind: Service
metadata:
  name: olivesample-canary-svc
  namespace: olive-ns
spec:
  type: NodePort
  selector:
    app: olivesampleissuermeta
  ports:
  - port: 8085
    targetPort: 8085
    nodePort: 30090
